CREATE DATABASE T_Cleaveland;


USE T_Cleaveland;

CREATE TABLE MEDICOS(
IDMEDICO INT PRIMARY KEY IDENTITY,
NOME VARCHAR(250),
DATANASCIMENTO DATE,
CRM INT UNIQUE,
);

ALTER TABLE MEDICOS
ADD ATIVO VARCHAR(250);


INSERT MEDICOS (NOME, DATANASCIMENTO, CRM) VALUES ('ERIK', '2011-11-11','333');
INSERT MEDICOS (NOME, DATANASCIMENTO, CRM) VALUES ('HELENA', '2010-10-10','444');
INSERT MEDICOS (NOME, DATANASCIMENTO, CRM) VALUES ('ROBERTO', '2009-9-9','555');

SELECT * FROM MEDICOS ORDER BY IDMEDICO ASC;

UPDATE MEDICOS SET ATIVO = 'INATIVO' WHERE IDMEDICO = 3






